version: '3'

services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    network_mode: host
    volumes:
      - ./src:/mnt/locust
    working_dir: /mnt/locust
    command: -f load_test.py --master -H http://localhost:3030

  worker:
    image: locustio/locust
    network_mode: host
    volumes:
      - ./src:/mnt/locust
    working_dir: /mnt/locust
    command: -f load_test.py --worker --master-host localhost
  
